const escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function feedbackPage(account,environment){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>意见箱 · MUSE</title><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/feedback/style.css"><script src="/feedback/client.js" defer></script></head>
<body data-admin="${account.admin?'true':'false'}"><header><a class="brand" href="/" aria-label="返回 MUSE 工作间"><img src="/spider.png" alt="">MUSE</a><div class="identity">${escape(account.username)}${environment==='development'?' · 开发版':''}</div><a href="/">返回工作间 ↗</a></header>
<main><div class="heading"><div><p class="eyebrow">YOUR VOICE, OUR NEXT CHAPTER</p><h1>意见箱<span class="dot">.</span></h1><p class="muted">让每一次创作，更顺手一点。</p></div><span class="outline-icon" aria-hidden="true">✉</span></div>
<div class="layout"><section class="card compose"><h2>告诉我们你的想法</h2><p class="muted small">遇到了问题，或有一个期待的新功能？都可以写在这里。</p><form id="feedback-form">
<label for="category">意见类型</label><select id="category" name="category"><option value="suggestion">功能建议</option><option value="bug">问题反馈</option><option value="other">其他意见</option></select>
<label for="title">一句话概括</label><input id="title" name="title" maxlength="120" placeholder="例如：希望支持批量下载剧本" required>
<label for="body">详细说明</label><textarea id="body" name="body" maxlength="8000" rows="7" placeholder="你在做什么？遇到了什么？你希望怎样改进？" required></textarea>
<label for="attachments">添加截图 <span class="muted">（选填）</span></label><div class="upload"><input id="attachments" name="attachments" type="file" accept="image/png,image/jpeg,image/webp" multiple><p class="muted small">最多 3 张，每张不超过 2 MB · PNG / JPG / WebP</p></div>
<p class="privacy">提交后仅你和管理员可见。请勿上传密码、API Key 或无关私人资料。意见不会自动加入 Agent 经验库。</p><button class="primary" id="submit" type="submit">提交意见 <span aria-hidden="true">↗</span></button><p id="form-status" role="status" aria-live="polite"></p></form></section>
<section class="records"><div class="list-heading"><div><p class="eyebrow">FEEDBACK & FOLLOW-UP</p><h2>${account.admin?'全部用户意见':'我的意见'}</h2></div>${account.admin?'<a class="export" href="/api/muse.feedback/export" download="muse-feedback.json">导出意见 ↓</a>':''}</div>
<div class="filters"><label class="sr-only" for="status-filter">处理状态</label><select id="status-filter"><option value="">全部状态</option><option value="new">待查看</option><option value="reviewing">处理中</option><option value="planned">已排期</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select><button class="quiet" id="refresh" type="button">刷新</button></div>
<p id="list-status" role="status" aria-live="polite"></p><div id="feedback-list"></div><button class="quiet" id="more" type="button" hidden>加载更多</button></section></div><footer>你的反馈将作为后续更新的参考，由管理员评估与确认。</footer></main></body></html>`;}
